### ISSUE TITLE
Concurrency Issues

### ISSUE THREAD

**Issue by vidhvath28** [102/belgrade-weather#6]
Risk of Data Corruption: If multiple instances of the script are run simultaneously, there’s a risk of race conditions leading to data corruption in history.csv. Implementing a locking mechanism could help mitigate this risk.

**Comment by vidhvath28** [comment]
@102  I would like to work on this issue, kindly assign this issue to me

**Comment by vidhvath28** [comment]
@flat-data  I did not receive any updates on the PR I have submitted.

**Comment by 102** [comment]
@vidhvath28 
> 
Risk of Data Corruption: If multiple instances of the script are run simultaneously, there’s a risk of race conditions leading to data corruption in history.csv. Implementing a locking mechanism could help mitigate this risk.

why would they run simultaneously? This is not really a risk since the script is invoked per cronjob once an hour
